application: stidy
runtime: go116  # or another supported version
api_version: go1

instance_class: F1

handlers:
- url: /.*
  script: _go_app

automatic_scaling:
  min_instances: 0
  max_instances: 1