// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Name string `json:"name"`
	List int64  `json:"list"`
}

type TaskList struct {
	ID    int64    `json:"id"`
	Users []int64  `json:"users"`
	Name  string   `json:"name"`
	Tasks []*int64 `json:"tasks"`
}

type Todo struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	CreatedAt   time.Time  `json:"createdAt"`
	ModifiedAt  time.Time  `json:"modifiedAt"`
	CompletedAt *time.Time `json:"completedAt"`
	List        int64      `json:"list"`
}

type User struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Lists []int64 `json:"lists"`
}

type UserAuth struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}
